export const LOAD_USERS_START ="LOAD_USERS_START";
export const LOAD_USERS_SUCCESS ="LOAD_USERS_SUCCESS";
export const LOAD_USERS_ERROR ="LOAD_USERS_ERROR";

export const CREATE_USERS_START ="CREATE_USERS_START";
export const CREATE_USERS_SUCCESS ="CREATE_USERS_SUCCESS";
export const CREATE_USERS_ERROR ="CREATE_USERS_ERROR";

export const DELETE_USERS_START =  "DELETE_USERS_START";
export const DELETE_USERS_SUCCESS ="DELETE_USERS_SUCCESS";
export const DELETE_USERS_ERROR =  "DELETE_USERS_ERROR";

export const UPDATE_USERS_START =  "UPDATE_USERS_START";
export const UPDATE_USERS_SUCCESS ="UPDATE_USERS_SUCCESS";
export const UPDATE_USERS_ERROR =  "UPDATE_USERS_ERROR";